collections:
  - posts
# Prose.io
prose:
  #rooturl: '_posts'
  #siteurl: 'https://maxgit.maxgoldhouse.com/'
  #media: 'images'
  #ignore:
  #  - index.md
  #  - _config.yml
 #   - /_layouts
 #   - /_includes
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'select'
          label: 'Template'
          #options: ['Full Width','Right Sidebar','Left Sidebar',]
          options: 'http://maxgit.maxgoldhouse.com/metadata/post_templates.jsonp'
      - name: 'title'
        field:
          element: 'text'
          label: 'Page Title'
      - name: 'categories'
        field:
          element: 'select'
          label: 'Category'
          options: 'http://codeship.com/documentation/metadata/categories.jsonp'
      - name: 'tags'
        field:
            element: 'multiselect'
            label: 'Tags'
            placeholder: 'Choose Tags'
            alterable: true
            #options: 'http://codeship.com/documentation/metadata/tags.jsonp'
      - name: 'weight'
        field:
          element: 'number'
          label: 'Page Weight'
          help: 'Used for sorting subpages in listings'
          value: 50
      - name: 'weight'
        field:
          element: 'text'
          label: 'SEO Description'
          help: 'Shows in Search Engine Listings'
